/**
******************************************************************************
* @file      syscalls.c
* @author    Auto-generated by STM32CubeIDE
* @brief     STM32CubeIDE Minimal System calls file
*
*            For more information about which c-functions
*            need which of these lowlevel functions
*            please consult the Newlib libc-manual
******************************************************************************
* @attention
*
* Copyright (c) 2020-2022 STMicroelectronics.
* All rights reserved.
*
* This software is licensed under terms that can be found in the LICENSE file
* in the root directory of this software component.
* If no LICENSE file comes with this software, it is provided AS-IS.
*
******************************************************************************
*/
// NOLINTBEGIN
/* Includes */
#include <errno.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <sys/time.h>
#include <sys/times.h>
#include <time.h>

#include "main.h"
#include "usart.h"

/* Variables */
extern int __io_putchar(int ch) __attribute__((weak));
extern int __io_getchar(void) __attribute__((weak));

char *__env[1] = {0};
char **environ = __env;

/* Functions */
void initialise_monitor_handles() {}

__attribute__((used)) int _getpid(void) { return 1; }

__attribute__((used)) int _kill(int pid, int sig) {
  (void)pid;
  (void)sig;
  errno = EINVAL;
  return -1;
}

__attribute__((used)) void _exit(int status) {
  _kill(status, -1);
  while (1) {
  } /* Make sure we hang here */
}

__attribute__((weak, used)) int _read(int file, char *ptr, int len) {
  // HAL_UART_Transmit(&huart1, "read\r\n", 6, HAL_MAX_DELAY);
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    *ptr++ = __io_getchar();
  }

  return len;
}

__attribute__((weak, used)) int _write(int file, char *ptr, int len) {
  (void)file;
  int DataIdx;

  for (DataIdx = 0; DataIdx < len; DataIdx++) {
    __io_putchar(*ptr++);
  }
  return len;
}

__attribute__((used)) int _close(int file) {
  // HAL_UART_Transmit(&huart1, "close\r\n", 7, HAL_MAX_DELAY);
  (void)file;
  return -1;
}

__attribute__((used)) int _fstat(int file, struct stat *st) {
  // HAL_UART_Transmit(&huart1, "fstat\r\n", 7, HAL_MAX_DELAY);
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

__attribute__((used)) int _isatty(int file) {
  // HAL_UART_Transmit(&huart1, "isatty\r\n", 8, HAL_MAX_DELAY);
  (void)file;
  return 1;
}

__attribute__((used)) int _lseek(int file, int ptr, int dir) {
  // HAL_UART_Transmit(&huart1, "lseek\r\n", 7, HAL_MAX_DELAY);
  (void)file;
  (void)ptr;
  (void)dir;
  return 0;
}

__attribute__((weak, used)) int _open(char *path, int flags, ...) {
  (void)path;
  (void)flags;
  /* Pretend like we always fail */
  return -1;
}

__attribute__((used)) int _wait(int *status) {
  // HAL_UART_Transmit(&huart1, "wait\r\n", 6, HAL_MAX_DELAY);
  (void)status;
  errno = ECHILD;
  return -1;
}

__attribute__((used)) int _unlink(char *name) {
  // HAL_UART_Transmit(&huart1, "unlink\r\n", 8, HAL_MAX_DELAY);
  (void)name;
  errno = ENOENT;
  return -1;
}

__attribute__((used)) int _times(struct tms *buf) {
  // HAL_UART_Transmit(&huart1, "times\r\n", 7, HAL_MAX_DELAY);
  (void)buf;
  return -1;
}

__attribute__((used)) int _stat(char *file, struct stat *st) {
  // HAL_UART_Transmit(&huart1, "stat\r\n", 6, HAL_MAX_DELAY);
  (void)file;
  st->st_mode = S_IFCHR;
  return 0;
}

__attribute__((used)) int _link(char *old, char *new) {
  // HAL_UART_Transmit(&huart1, "link\r\n", 6, HAL_MAX_DELAY);
  (void)old;
  (void)new;
  errno = EMLINK;
  return -1;
}

__attribute__((used)) int _fork(void) {
  // HAL_UART_Transmit(&huart1, "fork\r\n", 6, HAL_MAX_DELAY);
  errno = EAGAIN;
  return -1;
}

__attribute__((used)) int _execve(char *name, char **argv, char **env) {
  // HAL_UART_Transmit(&huart1, "execve\r\n", 8, HAL_MAX_DELAY);
  (void)name;
  (void)argv;
  (void)env;
  errno = ENOMEM;
  return -1;
}
// NOLINTEND
